version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.10.0  
    steps:
      - checkout  
      - run: docker build .
      - run: docker run -p 3000:3000 
      #     name: Install Dependencies
      #     command: npm install  
      # - run:
      #     name: Build the React App
      #     command: npm start
            
      
      
workflows:
  version: 2
  build:
    jobs:
      - build
