version: 2.1

jobs:
  build:
    docker:
      - image: alpine:latest  # Alpine-based Node.js Docker image
    services:
      - docker:  # Enable Docker service for Docker-in-Docker support
    steps:
      - checkout  # Checkout the code from your repository

      # Install Docker in the Alpine image
      - run:
          name: Install Docker
          command: |
            apk add --no-cache docker  # Install Docker inside the Alpine container

      # Build the Docker image
      - run:
          name: Build Docker image
          command: docker build -t react-app .  # Build Docker image with the 'react-app' tag

      # Run the Docker container
      - run:
          name: Run Docker container
          command: docker run -d -p 3000:3000 react-app  # Run in detached mode with port mapping

workflows:
  version: 2
  build:
    jobs:
      - build
