version: 2.1
 
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Check current user
          command: whoami


# version: 2.1

# jobs:
#   build:
#     docker:
#       # - image: cimg/node:23.10.0
#       - image: ubuntu:latest
#     steps:
      
#       - checkout
#       - run:
#         command : whoami
      # - run: npm install
      # - run: npm test
      # - run: npm run build  # Make sure to build the app here for production
#       - persist_to_workspace:
#           root: .
#           paths:
#             # - build/
#             - src/  # Persist the build directory instead of individual files

#   deploy:
#     docker:
#       - image: amazon/aws-cli
#     steps:
#       - run:
#           name: Install tar
#           command: yum install -y tar gzip
#       - checkout
#       - attach_workspace:
#           at: /workspace
#       - run:
#           name: Configure AWS Credentials
#           command: |
#             aws configure set aws_access_key_id $jammu
#             aws configure set aws_secret_access_key $kammu
#             # aws configure set region $AWS_REGION  # Ensure the region is set
#       - run:
#           name: Deploy to S3
#           command: |
#             aws s3 sync /workspace/src/ s3://amankattusajhedar/ --delete

# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
