version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.10.0  
    steps:
      - checkout  
      - run:
          name: Build Docker image
          command: docker build -t react-app .  # Build Docker image with tag 'react-app'
          
      # Run the Docker container
      - run:
          name: Run Docker container
          command: docker run -d -p 3000:3000 react-app
      #     name: Install Dependencies
      #     command: npm install  
      # - run:
      #     name: Build the React App
      #     command: npm start
            
      
      
workflows:
  version: 2
  build:
    jobs:
      - build
