version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.10.0  # Use the Node.js ocker image
    services:
      - docker  # Enable Docker service to access the Docker daemon
    steps:
      - checkout  # Checkout the repository
      
      # Install Docker CLI inside the container if needed
      - run:
          name: Install Docker CLI
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t react-app .  # Build Docker image with tag 'react-app'
          
      # Run the Docker container
      - run:
          name: Run Docker container
          command: docker run -d -p 3000:3000 react-app  # Run in detached mode with port mapping

workflows:
  version: 2
  build:
    jobs:
      - build
