version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.10.0  # Using the Node.js image for your app
    steps:
      - checkout  # Check out your source code
      - run:
          name: Check Node Version
          command: node --version  # Verify that Node.js is installed correctly
        # Install all project dependencies
      - run: npm install
      - run:
          name: Run Development Server
          command: npm run build
      - run:
          command: |
            npm install -g serve  # Install 'serve' package globally
            serve -s build -l 5000 &  # Serve the build on port 5000 in the background
            sleep 10  # Allow the server to start (you can add additional steps to test)
            curl http://localhost:5000
  # Start the development server
workflows:
  version: 2
  build:
    jobs:
      - build
