version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:23.10.0
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the React App
          command: npm run build  # Use 'npm run build' instead of 'npm start'
          
  deploy:
    docker:
      - image: circleci/python:3.8  # We use the Python image because `awscli` is easier to install in Python-based images
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli
      - run:
          name: Deploy to AWS S3
          command: |
            aws s3 sync ./build/ s3://amankattusajhedar/ --delete --region $AWS_REGION

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
