jobs:
  build:
    docker:
      - image: cimg/node:23.10.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Serve Globally
          command: npm install -g serve --unsafe-perm=true
      - run:
          name: Build the React App
          command: npm run build
      - run:
          name: Serve the Build
          command: |
            serve -s build -l 5000 &
            sleep 10  # Allow the server to start
            curl http://localhost:5000  # Check if the server is running
workflows:
  version: 2
  build:
    jobs:
      - build
